// Generated by CoffeeScript 1.8.0
var Attribute, Expressions, Predications, exports, u;

u = require('underscore');

Expressions = require('./expressions');

Predications = require('./predications');

Attribute = (function() {
  u(Attribute.prototype).extend(Expressions, Predications);

  function Attribute(relation, name) {
    this.relation = relation;
    this.name = name;
  }

  return Attribute;

})();

exports = module.exports = Attribute;
