// Generated by CoffeeScript 1.8.0
var InsertManager, SqlLiteral, UpdateManager, u;

u = require('underscore');

InsertManager = require('./insert-manager');

UpdateManager = require('./update-manager');

SqlLiteral = require('./nodes/sql-literal');

u.extend(module.exports, {
  compileInsert: function(values) {
    var im;
    im = this.createInsert();
    im.insert(values);
    return im;
  },
  createInsert: function() {
    return new InsertManager(this.engine);
  },
  compileDelete: function() {
    var dm;
    dm = new DeleteManager(this.engine);
    dm.wheres(this.ctx.wheres);
    dm.from(this.ctx.froms);
    return dm;
  },
  compileUpdate: function(values) {
    var relation, um;
    um = new UpdateManager(this.engine);
    relation = values.constructor === SqlLiteral ? this.ctx.from : values[0][0].relation;
    um.table(relation);
    um.set(values);
    if (this.ast.limit != null) {
      um.take(this.ast.limit.expr);
    }
    um.order(this.ast.orders);
    um.wheres = this.ctx.wheres;
    return um;
  }
});
