// Generated by CoffeeScript 1.8.0
var CaseBuilder, InsertManager, Nodes, Range, Rel, SelectManager, Table, UpdateManager, Visitors, exports;

Nodes = require('./nodes');

Range = require('./range');

Table = require('./table');

Visitors = require('./visitors');

SelectManager = require('./select-manager');

InsertManager = require('./insert-manager');

UpdateManager = require('./update-manager');

CaseBuilder = require('./nodes/case-builder');

Rel = {
  VERSION: '0.0.1',
  sql: function(rawSql) {
    return new Nodes.SqlLiteral(rawSql);
  },
  star: function() {
    return this.sql('*');
  },
  range: function(start, finish) {
    return new Range(start, finish);
  },
  Nodes: Nodes,
  Table: Table,
  Visitors: Visitors,
  Collectors: require('./collectors'),
  SelectManager: SelectManager,
  InsertManager: InsertManager,
  UpdateManager: UpdateManager
};

exports = module.exports = Rel;
