// Generated by CoffeeScript 1.8.0
var FactoryMethods, SQLString, TreeManager, Visitors, exports, u;

u = require('underscore');

FactoryMethods = require('./factory-methods');

Visitors = require('./visitors');

SQLString = require('./collectors/sql-string');

TreeManager = (function() {
  u.extend(TreeManager.prototype, FactoryMethods);

  function TreeManager(engine) {
    this.engine = engine;
    this.visitor = this.engine.visitor();
    this.ast = null;
    this.ctx = null;
  }

  TreeManager.prototype.toDot = function() {
    return new Visitors.Dot().accept(this.ast);
  };

  TreeManager.prototype.toSql = function() {
    var collector;
    collector = new SQLString;
    this.visitor.accept(this.ast, collector);
    return collector.value;
  };

  TreeManager.prototype.initializeCopy = function(other) {
    TreeManager.__super__.initializeCopy.call(this);
    return this.ast = u(this.ast).clone();
  };

  TreeManager.prototype.where = function(expr) {
    if (TreeManager === expr.constructor) {
      expr = expr.ast;
    }
    this.ctx.wheres.push(expr);
    return this;
  };

  return TreeManager;

})();

exports = module.exports = TreeManager;
