// Generated by CoffeeScript 1.8.0
var Dot, MSSQL, OrderClauses, Postgresql, ToSql, WhereSql, u,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

u = require('underscore');

Dot = require('./visitors/dot');

Postgresql = require('./visitors/postgresql');

ToSql = require('./visitors/to-sql');

MSSQL = require('./visitors/mssql');

u.extend(module.exports, {
  Dot: Dot,
  visitor: function() {
    return new Postgresql();
  },
  ToSql: ToSql,
  MSSQL: MSSQL,
  JoinSql: {
    visitRelNodesSelectCore: function(o) {
      return (o.source.right.map((function(_this) {
        return function(j) {
          return _this.visit(j);
        };
      })(this))).join(' ');
    }
  },
  OrderClauses: OrderClauses = (function(_super) {
    __extends(OrderClauses, _super);

    function OrderClauses() {
      return OrderClauses.__super__.constructor.apply(this, arguments);
    }

    OrderClauses.prototype.visitRelNodesSelectStatement = function(o) {
      return o.orders.map((function(_this) {
        return function(x) {
          return _this.visit(x);
        };
      })(this));
    };

    return OrderClauses;

  })(ToSql),
  WhereSql: WhereSql = (function(_super) {
    __extends(WhereSql, _super);

    function WhereSql() {
      return WhereSql.__super__.constructor.apply(this, arguments);
    }

    WhereSql.prototype.visitRelNodesSelectCore = function(o) {
      return "WHERE " + ((o.wheres.map((function(_this) {
        return function(x) {
          return _this.visit(x);
        };
      })(this))).join(' AND '));
    };

    return WhereSql;

  })(ToSql)
});
