// Generated by CoffeeScript 1.8.0
var Bind, BindParam, u;

u = require('underscore');

BindParam = require('../nodes/bind-param');

Bind = (function() {
  function Bind() {
    this.value = [];
  }

  Bind.prototype.append = function(str) {
    this.value.push(str);
    return this;
  };

  Bind.prototype.addBind = function(bind) {
    this.value.push(bind);
    return this;
  };

  Bind.prototype.substituteBinds = function(bvs) {
    bvs = bvs.slice(0);
    return u.map(this.value, function(val) {
      if (val.constructor === BindParam) {
        return bvs.shift();
      } else {
        return val;
      }
    });
  };

  Bind.prototype.compile = function(bvs) {
    return this.substituteBinds(bvs).join('');
  };

  return Bind;

})();

module.exports = Bind;
