// Generated by CoffeeScript 1.8.0
var SQLString;

SQLString = (function() {
  function SQLString() {
    this.value = "";
  }

  SQLString.prototype.append = function(str) {
    this.value += str;
    return this;
  };

  SQLString.prototype.addBind = function(bv) {
    return this.append(bv);
  };

  SQLString.prototype.compile = function(bvs) {
    return this.value;
  };

  return SQLString;

})();

module.exports = SQLString;
