// Generated by CoffeeScript 1.8.0
var As, Binary,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Binary = require('./binary');

As = (function(_super) {
  __extends(As, _super);

  function As() {
    return As.__super__.constructor.apply(this, arguments);
  }

  return As;

})(Binary);

module.exports = As;
