// Generated by CoffeeScript 1.8.0
var Case, CaseBuilder, Expressions, Node, Predications, exports, u,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

u = require('underscore');

Node = require('./node');

Expressions = require('../expressions');

Predications = require('../predications');

CaseBuilder = (function() {
  function CaseBuilder(_base) {
    this._base = _base;
    this._cases = [];
    this._else = void 0;
  }

  CaseBuilder.prototype.when = function(cond, res) {
    this._cases.push([cond, res]);
    return this;
  };

  CaseBuilder.prototype["else"] = function(res) {
    this._else = res;
    return this;
  };

  CaseBuilder.prototype.end = function() {
    return new Case(this._base, this._cases, this._else);
  };

  return CaseBuilder;

})();

Case = (function(_super) {
  __extends(Case, _super);

  u(Case.prototype).extend(Expressions, Predications);

  function Case(_base, _cases, _else) {
    this._base = _base;
    this._cases = _cases;
    this._else = _else;
  }

  return Case;

})(Node);

exports = module.exports = CaseBuilder;
