// Generated by CoffeeScript 1.8.0
var ConstLit, Expressions, Predications, SqlLiteral, Unary, exports, u,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  __slice = [].slice;

u = require('underscore');

Unary = require('./unary');

SqlLiteral = require('./sql-literal');

Expressions = require('../expressions');

Predications = require('../predications');

ConstLit = (function(_super) {
  __extends(ConstLit, _super);

  u(ConstLit.prototype).extend(Expressions, Predications);

  function ConstLit() {
    var args;
    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    ConstLit.__super__.constructor.apply(this, args);
  }

  return ConstLit;

})(Unary);

exports = module.exports = ConstLit;
