// Generated by CoffeeScript 1.8.0
var Exists, FunctionNode,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

FunctionNode = require('./function-node');

Exists = (function(_super) {
  __extends(Exists, _super);

  function Exists() {
    return Exists.__super__.constructor.apply(this, arguments);
  }

  return Exists;

})(FunctionNode);

module.exports = Exists;
