// Generated by CoffeeScript 1.8.0
var Grouping, Unary,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Unary = require('./unary');

Grouping = (function(_super) {
  __extends(Grouping, _super);

  function Grouping() {
    return Grouping.__super__.constructor.apply(this, arguments);
  }

  return Grouping;

})(Unary);

module.exports = Grouping;
