// Generated by CoffeeScript 1.8.0
var Equality, In,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Equality = require('./equality');

In = (function(_super) {
  __extends(In, _super);

  function In() {
    return In.__super__.constructor.apply(this, arguments);
  }

  return In;

})(Equality);

module.exports = In;
