// Generated by CoffeeScript 1.8.0
var Binary, Intersect,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Binary = require('./binary');

Intersect = (function(_super) {
  __extends(Intersect, _super);

  function Intersect() {
    return Intersect.__super__.constructor.apply(this, arguments);
  }

  return Intersect;

})(Binary);

module.exports = Intersect;
