// Generated by CoffeeScript 1.8.0
var Binary, Join,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Binary = require('./binary');

Join = (function(_super) {
  __extends(Join, _super);

  function Join() {
    return Join.__super__.constructor.apply(this, arguments);
  }

  return Join;

})(Binary);

module.exports = Join;
