// Generated by CoffeeScript 1.8.0
var Binary, LessThan,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Binary = require('./binary');

LessThan = (function(_super) {
  __extends(LessThan, _super);

  function LessThan() {
    return LessThan.__super__.constructor.apply(this, arguments);
  }

  return LessThan;

})(Binary);

module.exports = LessThan;
