// Generated by CoffeeScript 1.8.0
var Node, Nodes, SQLString, Visitors, exports;

Nodes = require('./index');

Visitors = require('../visitors');

SQLString = require('../collectors/sql-string');

Node = (function() {
  function Node() {}

  Node.prototype.not = function() {
    return new Nodes.Not(this);
  };

  Node.prototype.or = function(right) {
    return new Nodes.Grouping(new Nodes.Or(this, right));
  };

  Node.prototype.and = function(right) {
    return new Nodes.And([this, right]);
  };

  Node.prototype.toSql = function(engine) {
    var collector;
    if (engine == null) {
      throw new Error("Node#toSql: missing engine");
    }
    collector = new SQLString;
    engine.visitor().accept(this, collector);
    return collector.value;
  };

  return Node;

})();

exports = module.exports = Node;
