// Generated by CoffeeScript 1.8.0
var Binary, NotEqual,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Binary = require('./binary');

NotEqual = (function(_super) {
  __extends(NotEqual, _super);

  function NotEqual() {
    return NotEqual.__super__.constructor.apply(this, arguments);
  }

  return NotEqual;

})(Binary);

module.exports = NotEqual;
