// Generated by CoffeeScript 1.8.0
var Binary, NotRegexp,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Binary = require('./binary');

NotRegexp = (function(_super) {
  __extends(NotRegexp, _super);

  function NotRegexp() {
    return NotRegexp.__super__.constructor.apply(this, arguments);
  }

  return NotRegexp;

})(Binary);

module.exports = NotRegexp;
