// Generated by CoffeeScript 1.8.0
var Binary, Over,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Binary = require('./binary');

Over = (function(_super) {
  __extends(Over, _super);

  function Over(left, right) {
    if (right == null) {
      right = null;
    }
    Over.__super__.constructor.call(this, left, right);
    this.operator = "OVER";
  }

  return Over;

})(Binary);

module.exports = Over;
