// Generated by CoffeeScript 1.8.0
var Binary, Regexp,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Binary = require('./binary');

Regexp = (function(_super) {
  __extends(Regexp, _super);

  function Regexp() {
    return Regexp.__super__.constructor.apply(this, arguments);
  }

  return Regexp;

})(Binary);

module.exports = Regexp;
