// Generated by CoffeeScript 1.8.0
var Expressions, Predications, SqlLiteral, exports, u;

u = require('underscore');

Expressions = require('../expressions');

Predications = require('../predications');

SqlLiteral = (function() {
  u(SqlLiteral.prototype).extend(Expressions, Predications);

  function SqlLiteral(value) {
    this.value = value;
  }

  SqlLiteral.prototype.toString = function() {
    return "" + this.value;
  };

  return SqlLiteral;

})();

exports = module.exports = SqlLiteral;
