// Generated by CoffeeScript 1.8.0
var Attribute, Binary, TableAlias,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Attribute = require('../attribute');

Binary = require('./binary');

TableAlias = (function(_super) {
  __extends(TableAlias, _super);

  function TableAlias(left, right) {
    this.left = left;
    this.right = right;
    TableAlias.__super__.constructor.call(this, this.left, this.right);
    this.name = this.right;
    this.relation = this.left;
    this.tableAlias = this.name;
    this.tableName = this.relation.name;
  }

  TableAlias.prototype.column = function(name) {
    return new Attribute(this, name);
  };

  return TableAlias;

})(Binary);

module.exports = TableAlias;
