// Generated by CoffeeScript 1.8.0
var Unary, UnqualifiedColumn,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Unary = require('./unary');

UnqualifiedColumn = (function(_super) {
  __extends(UnqualifiedColumn, _super);

  function UnqualifiedColumn() {
    return UnqualifiedColumn.__super__.constructor.apply(this, arguments);
  }

  UnqualifiedColumn.prototype.attribute = function(attr) {
    if (attr != null) {
      return this.expr = attr;
    } else {
      return this.expr;
    }
  };

  Object.defineProperty(UnqualifiedColumn.prototype, 'relation', {
    get: function() {
      return this.expr.relation;
    }
  });

  Object.defineProperty(UnqualifiedColumn.prototype, 'column', {
    get: function() {
      return this.expr.column;
    }
  });

  Object.defineProperty(UnqualifiedColumn.prototype, 'name', {
    get: function() {
      return this.expr.name;
    }
  });

  return UnqualifiedColumn;

})(Unary);

module.exports = UnqualifiedColumn;
