// Generated by CoffeeScript 1.8.0
var Unary, With,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Unary = require('./unary');

With = (function(_super) {
  __extends(With, _super);

  function With() {
    return With.__super__.constructor.apply(this, arguments);
  }

  Object.defineProperty(With.prototype, 'children', {
    get: function() {
      return this.expr;
    },
    set: function(expr) {
      this.expr = expr;
    }
  });

  return With;

})(Unary);

module.exports = With;
