// Generated by CoffeeScript 1.8.0
var Visitor, exports;

Visitor = (function() {
  function Visitor() {}

  Visitor.prototype.accept = function(object, collector) {
    return this.visit(object, collector);
  };

  Visitor.prototype.visit = function(object, collector) {
    var type, _ref;
    type = (_ref = object != null ? object.constructor.name : void 0) != null ? _ref : 'Null';
    return this["visitRelNodes" + type](object);
  };

  return Visitor;

})();

exports = module.exports = Visitor;
